fn main() {
    cc::Build::new()
        .cpp(true)
        .files(&[
            "src/swift/demangle.cpp",
            "src/swift/lib/Demangler.cpp",
            "src/swift/lib/Context.cpp",
            "src/swift/lib/Errors.cpp",
            "src/swift/lib/ManglingUtils.cpp",
            "src/swift/lib/NodeDumper.cpp",
            "src/swift/lib/NodePrinter.cpp",
            "src/swift/lib/OldDemangler.cpp",
            "src/swift/lib/Punycode.cpp",
        ])
        .flag_if_supported("-std=c++17")
        .flag_if_supported("-fpermissive")
        .flag("-DLLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=1")
        .flag("-DSWIFT_STDLIB_HAS_TYPE_PRINTING")
        .flag("-DSWIFT_SUPPORT_OLD_MANGLING")
        .warnings(false)
        .include("src/swift/include")
        .compile("demangle");
}
